### ISSUE TITLE
Any roadmap on when this may be ready?

### ISSUE THREAD

**Issue by CompeyDev** [itschip/guildedgo#1]
I'm attempting to make a guilded RESTful API, similar to Lanyard, etc. for discord. Planning on writing it in go, but I do not find any proper guilded go libraries. This looks good, so when is a proper release date for this?

**Comment by itschip** [comment]
Hi @CompeyDev , there is no current roadmap for the moment. I've been occupied with other projects of mine for the past couple of days. 

This is however a project I really like to see through, so I'll make sure to write up a initial roadmap that I/we can extend upon as this grows,

As it goes for the release, I do want a somewhat more fundemental base first. Should not take long to accomplish such,

**Comment by CompeyDev** [comment]
Ah. Noted, will probably use another language then.
